spring:
  datasource:
    url: jdbc:mysql://192.168.0.102:3306/authforge?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

server:
  port: 9999

logging:
  level:
    org.springframework.security: DEBUG
    com.zhouzhou.authforge: DEBUG

auth:
  token:
    # 令牌生成类型：UUID 或 JWT
    type: JWT
    jwt:
      # JWT签发者
      issuer: auth-forge
      # JWT密钥（生产环境请使用更安全的密钥管理方式）
      secret: ${JWT_SECRET:your-256-bit-secret-key-should-be-changed-in-production}
      # 访问令牌过期时间（分钟）
      access-token-expiration-minutes: 30
      # 刷新令牌过期时间（分钟）
      refresh-token-expiration-minutes: 1440
